### ISSUE TITLE
Compilation failure during 'make' process

### ISSUE THREAD

**Issue by yuber30** [trixi-framework/HOHQMesh#102]
Dear author,

I encountered a compilation failure issue when running the **make** command. The error occurred both when using **spack** and making directly from the source code. I wonder if this is related to the version of **gfortran**.

I would greatly appreciate any insights or suggestions you might have to help me resolve this issue. Thank you very much for your time and assistance.

> **make** directly

```
gfortran-13 -c -cpp -O  -o MeshGeneratorMethods.o ./Source/Mesh/MeshGeneratorMethods.f90

in gfc_format_decoder, at fortran/error.cc:1078
Please submit a full bug report, with preprocessed source (by using -freport-bug).
See <https://github.com/Homebrew/homebrew-core/issues> for instructions.
make: *** [MeshGeneratorMethods.o] Error 1
```

> using **spack**

```
 48    make[2]: *** No rule to make target 'Source/CMakeFiles/hohqmesh.dir/
           depend'.  Stop.
 49    make[2]: Leaving directory '/private/tmp/root/spack-stage/spack-stag
           e-hohqmesh-1.5.0-cafk3gru6b547tv3joiyy2xk26h4g2ug/spack-build-cafk3g
           r'
 50    make[1]: *** [CMakeFiles/Makefile2:102: Source/CMakeFiles/hohqmesh.d
           ir/all] Error 2
 51    make[1]: Leaving directory '/private/tmp/root/spack-stage/spack-stag
           e-hohqmesh-1.5.0-cafk3gru6b547tv3joiyy2xk26h4g2ug/spack-build-cafk3g
           r'
 52    make: *** [Makefile:139: all] Error 2
```

Best regrads
Yuber

**Comment by andrewwinters5000** [comment]
I do not encounter this error on my machine when using `make`. I am using the compiler `GNU Fortran (Homebrew GCC 13.1.0) 13.1.0`. What version of `gfortran` are you using?

**Comment by andrewwinters5000** [comment]
I also added a [CI job](https://github.com/trixi-framework/HOHQMesh/actions/runs/10074127901/job/27849568786) for `gfortran-13` and the code successfully compiles on the github runners

**Comment by yuber30** [comment]
Thank you for your reply. I am using the compiler `GNU Fortran (GCC) 14.1.0`.

**Comment by DavidAKopriva** [comment]
The first set of messages references a bug in gfortran and the second with make. As Andrew noted, HOHQMesh is tested against numerous compilers on mac/win/linux so we don't see that on our own machines or on GitHub. At the risk of sounding like "Is your computer turned on", are you able to use make and gfortran on a simple program of your own? If not, there is probably an installation error. If yes, then it may be something that was added to the latest versions of gfortran, the version of which we might have to skip until the bug is fixed.

**Comment by yuber30** [comment]
Thank you very much for your reply. After restarting the computer, this problem disappeared strangely. Now the `make` command can compile successfully. Thank you very much for the help of both teachers.
